### ISSUE TITLE
任迪：测试环境加个NPC领元宝吧，节点也都打开

### ISSUE THREAD

**Issue by hank-mir** [Starzlin/98DataRepair#1]

**Comment by Starzlin** [comment]
好的任总，安排上

**Comment by Starzlin** [comment]
task“测试环境添加NPC领元宝”进展：
1、各地图的“活动大使”，都加入了领元宝， 无条件限制，直接点击就可以领
2、只在测试环境中添加，代码库中未添加
![QQ_1725157662095](https://github.com/user-attachments/assets/f9425bbc-9100-44ee-805f-6e089a688607)

**Comment by Starzlin** [comment]
task“开放测试环境游戏节点”进展：
已从下图“玛法初征”，开放到“龙耀雪山”
![QQ_1725157706392](https://github.com/user-attachments/assets/aa88fce5-becb-4613-a597-1d3ae031fd35)
重启后生效，看是否现在需要重启？ @hank-mir

**Comment by hank-mir** [comment]
现在有兄弟在测试，中午投个吃饭空闲时间重启吧

**Comment by Starzlin** [comment]
已完成
