### ISSUE TITLE
怪兽：[引擎]铭文，洗到5001必出那手时候不会顶掉烈火 铁定是在第一个位置

### ISSUE THREAD

**Issue by hank-mir** [Starzlin/98DataRepair#23]
![Screenshot_20240904_203926_com.tencent.mm.jpg](https://github.com/user-attachments/assets/c68dad13-bb51-4789-966e-a9574668e87d)

**Comment by Starzlin** [comment]
https://github.com/user-attachments/assets/44e2addc-e75a-45a8-b4de-32e1bdd1ffed
